#! /bin/bash -e

cd "$(dirname "$0")/.."

# Built-in Rails setup
# DISCUSSION: Not needed if running container.
# ./bin/setup --skip-server


# Create Kubernetes namespaces
# DISCUSSION: Is in the right place?
